spring.application.name=pagamentos
eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
server.port=0
eureka.instance.instance-id=${spring.application.name}:${random.int}

spring.datasource.url=jdbc:postgresql://localhost:5432/alurafood
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.flyway.enabled=true

resilience4j.circuitbreaker.instances.atualizaPedido.slidingWindowSize: 3
resilience4j.circuitbreaker.instances.atualizaPedido.minimumNumberOfCalls: 2
resilience4j.circuitbreaker.instances.atualizaPedido.waitDurationInOpenState: 50s